#Service that point to both deployment
#Selector must indicate both deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: deployment-1
    app: deployment-2
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
